version: '3'

networks:
  frontend:

services:
  flask-web:
    build: .
    ports:
      - "5000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    volumes:
      - ./app:/app  # Mount the local 'app' directory into the container

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - flask-web
    ports:
      - "81:81"
    networks:
      - frontend