version: '3'

services:
  flask-web:
    build: .
    volumes:
      - ./app:/app  # Mount the local 'app' directory into the container

  nginx:
    image: nginx:latest
    ports:
      - "5678:5678"
    depends_on:
      - flask-web
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
