version: '3'

services:
  flask-web:
    build: .
    ports:
      - "5000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - ./app:/app  # Mount the local 'app' directory into the container

  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    depends_on:
      - flask-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
