version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:5000"
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  flask-web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`flask.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.port=5000"
    expose:
      - "5000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - ./app:/app  # Mount the local 'app' directory into the container

 