version: '3'

services:
  flask-web:
    build: .
    volumes:
      - ./app:/app  # Mount the local 'app' directory into the container

  nginx:
    image: nginx:latest
    ports:
      - "5678:5678"
    depends_on:
      - flask-web
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - flask-web
      - nginx
